import { formatDate } from '@angular/common';

export class ordenesServicioModel {
  id_orden_servicio:              number;
  n_kilometraje_inicial:          number;
  n_kilometraje_final:            number;
  n_total:                        number;
  d_fecha_recepcion:              string;
  d_fecha_entrega:                string;
  t_hora_recepcion:               string;
  t_hora_entrega:                 string;
  n_horas_invertidas:             number;
  n_horas_perdidas:               number;
  s_riesgo:                       string;
  s_comentario_revision_tecnico:  string;
  s_comodin:                      string;
  s_img_firma_inicial:            string;
  s_img_firma_final:              string;
  b_con_cita:                     number;
  b_activo:                       number;
  id_cita:                        number;
  s_estatus_cita:                 string;
  d_fecha_cita:                   string;
  t_hora_cita:                    string;
  s_qr_cita:                      string;
  id_cliente:                     number;
  s_nombre:                       string;
  s_apellido_paterno:             string;
  s_apellido_materno:             string;
  n_telefono:                     string;
  s_direccion:                    string;
  id_vehiculo:                    number;
  s_marca_vehiculo:               string;
  s_modelo_vehiculo:              string;
  n_anio:                         number;
  s_placa:                        string;
  s_vin:                          string;
  s_kilometraje:                  string;
  id_servicio:                    number;
  s_tipo_servicio:                string;
  s_servicio:                     string;
  s_descripcion:                  string;
  n_precio:                       number;
  n_puntos_lealtad:               number;
  n_duracion_horas:               number;
  n_duracion_dias:                number;
  id_empleado:                    number;
  s_nombre_asesor:                string;
  s_apellido_paterno_asesor:      string;
  s_apellido_materno_asesor:      string;
  id_sucursal:                    number;
  s_sucursal:                     string;
  s_direccion_sucursal:           string;
  id_estatus_orden_servicio:      number;
  s_estatus_orden_servicio:       string;
  id_nivel_combustible:           number;
  s_nivel_combustible:            string;
  id_estatus_proceso:             number;
  s_estatus_proceso:              string;
  id_tipo_refaccion:              number;
  s_tipo_refaccion:               string;
  id_tipo_proveedor_refacciones:  number;
  s_tipo_proveedor_refacciones:   string;
  id_promocion:                   number;
  s_promocion:                    string;
  n_porcentaje_descuento:         number;
  id_anticipo:                    number;
  n_importe:                      number;
  s_url_imagen:                   string;


    constructor(ordenesServicioModel: Partial<ordenesServicioModel> = {})
    {
        this.id_orden_servicio              = ordenesServicioModel.id_orden_servicio             || this.getRandomID();
        this.n_kilometraje_inicial          = ordenesServicioModel.n_kilometraje_inicial         || 0;
        this.n_kilometraje_final            = ordenesServicioModel.n_kilometraje_final           || 0;
        this.n_total                        = ordenesServicioModel.n_total                       || 0;
        this.d_fecha_recepcion              = ordenesServicioModel.d_fecha_recepcion             || formatDate(new Date(), 'yyyy-MM-dd', 'en-US');
        this.d_fecha_entrega                = ordenesServicioModel.d_fecha_entrega               || formatDate(new Date(), 'yyyy-MM-dd', 'en-US');
        this.t_hora_recepcion               = ordenesServicioModel.t_hora_recepcion              || formatDate(new Date(), 'HH:mm:ss', 'en-US');
        this.t_hora_entrega                 = ordenesServicioModel.t_hora_entrega                || formatDate(new Date(), 'HH:mm:ss', 'en-US');
        this.n_horas_invertidas             = ordenesServicioModel.n_horas_invertidas            || 0;
        this.n_horas_perdidas               = ordenesServicioModel.n_horas_perdidas              || 0;
        this.s_riesgo                       = ordenesServicioModel.s_riesgo                      || '';
        this.s_comentario_revision_tecnico  = ordenesServicioModel.s_comentario_revision_tecnico || '';
        this.s_comodin                      = ordenesServicioModel.s_comodin                     || '';
        this.s_img_firma_inicial            = ordenesServicioModel.s_img_firma_inicial           || '';
        this.s_img_firma_final              = ordenesServicioModel.s_img_firma_final             || '';
        this.b_con_cita                     = ordenesServicioModel.b_con_cita                    || 0;
        this.b_activo                       = ordenesServicioModel.b_activo                      || 0;
        this.id_cita                        = ordenesServicioModel.id_cita                       || 0;
        this.s_estatus_cita                 = ordenesServicioModel.s_estatus_cita                || '';
        this.d_fecha_cita                   = ordenesServicioModel.d_fecha_cita                  || formatDate(new Date(), 'yyyy-MM-dd', 'en-US');
        this.t_hora_cita                    = ordenesServicioModel.t_hora_cita                   || formatDate(new Date(), 'HH:mm:ss', 'en-US');
        this.s_qr_cita                      = ordenesServicioModel.s_qr_cita                     || '';
        this.id_cliente                     = ordenesServicioModel.id_cliente                    || 0;
        this.s_nombre                       = ordenesServicioModel.s_nombre                      || '';
        this.s_apellido_paterno             = ordenesServicioModel.s_apellido_paterno            || '';
        this.s_apellido_materno             = ordenesServicioModel.s_apellido_materno            || '';
        this.n_telefono                     = ordenesServicioModel.n_telefono                    || '';
        this.s_direccion                    = ordenesServicioModel.s_direccion                   || '';
        this.id_vehiculo                    = ordenesServicioModel.id_vehiculo                   || 0;
        this.s_marca_vehiculo               = ordenesServicioModel.s_marca_vehiculo              || '';
        this.s_modelo_vehiculo              = ordenesServicioModel.s_modelo_vehiculo             || '';
        this.n_anio                         = ordenesServicioModel.n_anio                        || 0;
        this.s_placa                        = ordenesServicioModel.s_placa                       || '';
        this.s_vin                          = ordenesServicioModel.s_vin                         || '';
        this.s_kilometraje                  = ordenesServicioModel.s_kilometraje                 || '';
        this.id_servicio                    = ordenesServicioModel.id_servicio                   || 0;
        this.s_tipo_servicio                = ordenesServicioModel.s_tipo_servicio               || '';
        this.s_servicio                     = ordenesServicioModel.s_servicio                    || '';
        this.s_descripcion                  = ordenesServicioModel.s_descripcion                 || '';
        this.n_precio                       = ordenesServicioModel.n_precio                      || 0;
        this.n_puntos_lealtad               = ordenesServicioModel.n_puntos_lealtad              || 0;
        this.n_duracion_horas               = ordenesServicioModel.n_duracion_horas              || 0;
        this.n_duracion_dias                = ordenesServicioModel.n_duracion_dias               || 0;
        this.id_empleado                    = ordenesServicioModel.id_empleado                   || 0;
        this.s_nombre_asesor                = ordenesServicioModel.s_nombre_asesor               || '';
        this.s_apellido_paterno_asesor      = ordenesServicioModel.s_apellido_paterno_asesor     || '';
        this.s_apellido_materno_asesor      = ordenesServicioModel.s_apellido_materno_asesor     || '';
        this.id_sucursal                    = ordenesServicioModel.id_sucursal                   || 0;
        this.s_sucursal                     = ordenesServicioModel.s_sucursal                    || '';
        this.s_direccion_sucursal           = ordenesServicioModel.s_direccion_sucursal          || '';
        this.id_estatus_orden_servicio      = ordenesServicioModel.id_estatus_orden_servicio      || 0;
        this.s_estatus_orden_servicio       = ordenesServicioModel.s_estatus_orden_servicio       || '';
        this.id_nivel_combustible           = ordenesServicioModel.id_nivel_combustible           || 0;
        this.s_nivel_combustible            = ordenesServicioModel.s_nivel_combustible            || '';
        this.id_estatus_proceso             = ordenesServicioModel.id_estatus_proceso             || 0;
        this.s_estatus_proceso              = ordenesServicioModel.s_estatus_proceso              || '';
        this.id_tipo_refaccion              = ordenesServicioModel.id_tipo_refaccion              || 0;
        this.s_tipo_refaccion               = ordenesServicioModel.s_tipo_refaccion               || '';
        this.id_tipo_proveedor_refacciones   = ordenesServicioModel.id_tipo_proveedor_refacciones   || 0;
        this.s_tipo_proveedor_refacciones    = ordenesServicioModel.s_tipo_proveedor_refacciones    || '';
        this.id_promocion                   = ordenesServicioModel.id_promocion                    || 0;
        this.s_promocion                    = ordenesServicioModel.s_promocion                     || '';
        this.n_porcentaje_descuento         = ordenesServicioModel.n_porcentaje_descuento          || 0;
        this.id_anticipo                    = ordenesServicioModel.id_anticipo                     || 0;
        this.n_importe                      = ordenesServicioModel.n_importe                       || 0;
        this.s_url_imagen                   = ordenesServicioModel.s_url_imagen                    !;
    }


    public getRandomID(): number {
        const S4 = () => {
        return ((1 + Math.random()) * 0x10000) | 0;
        };
        return S4() + S4();
    }
}
