import { formatDate } from '@angular/common';

export class serviciosRequierenCotizacionModel {
  id_orden_servicio:              number;
  n_kilometraje_inicial:          number;
  n_kilometraje_final:            number;
  n_total:                        number;
  d_fecha_recepcion:              string;
  d_fecha_entrega:                string;
  t_hora_recepcion:               string;
  t_hora_entrega:                 string;
  n_horas_invertidas:             number;
  n_horas_perdidas:               number;
  s_riesgo:                       string;
  s_comentario_revision_tecnico:  string;
  s_comodin:                      string;
  s_img_firma_inicial:            string;
  s_img_firma_final:               string;
  b_con_cita:                     number;
  b_activo:                       number;
  n_duracion_recepcion:           number;
  t_hora_inicio_recepcion:        string;
  t_hora_fin_recepcion:           string;
  id_cita:                        number;
  s_estatus_cita:                 string;
  d_fecha_cita:                   string;
  t_hora_cita:                    string;
  s_qr_cita:                      string;
  id_cliente:                     number;
  s_nombre:                       string;
  s_apellido_paterno:             string;
  s_apellido_materno:             string;
  n_telefono:                     string;
  s_direccion:                    string;
  id_vehiculo:                    number;
  s_marca_vehiculo:               string;
  s_modelo_vehiculo:              string;
  n_anio:                         number;
  s_placa:                        string;
  s_vin:                          string;
  s_kilometraje:                  number;
  id_servicio:                    number;
  s_tipo_servicio:                string;
  s_servicio:                     string;
  s_descripcion:                  string;
  n_precio:                       number;
  n_puntos_lealtad:               number;
  n_duracion_horas:               number;
  n_duracion_dias:                number;
  id_tipo_revision:                number;
  id_empleado:                    number;
  s_nombre_asesor:                string;
  s_apellido_paterno_asesor:      string;
  s_apellido_materno_asesor:      string;
  id_sucursal:                    number;
  s_sucursal:                     string;
  s_direccion_sucursal:           string;
  id_estatus_orden_servicio:      number;
  s_estatus_orden_servicio:       string;
  id_nivel_combustible:           number;
  s_nivel_combustible:            string;
  id_estatus_proceso:             number;
  s_estatus_proceso:              string;
  id_clase_refaccion:             number;
  s_clase_refaccion:              string;
  id_tipo_proveedor_refacciones:  number;
  s_tipo_proveedor_refacciones:   string;
  id_promocion:                   number;
  s_promocion:                    string;
  n_porcentaje_descuento:         number;
  id_anticipo:                    number;
  n_importe:                      number;
  s_nombre_imagen:                string;
  s_url_imagen:                   string;


    constructor(serviciosRequierenCotizacionModel: Partial<serviciosRequierenCotizacionModel> = {})
    {
        this.id_orden_servicio              = serviciosRequierenCotizacionModel.id_orden_servicio             || this.getRandomID();
        this.n_kilometraje_inicial          = serviciosRequierenCotizacionModel.n_kilometraje_inicial         || 0;
        this.n_kilometraje_final            = serviciosRequierenCotizacionModel.n_kilometraje_final           || 0;
        this.n_total                        = serviciosRequierenCotizacionModel.n_total                       || 0;
        this.d_fecha_recepcion              = serviciosRequierenCotizacionModel.d_fecha_recepcion             || formatDate(new Date(), 'yyyy-MM-dd', 'en-US');
        this.d_fecha_entrega                = serviciosRequierenCotizacionModel.d_fecha_entrega               || '';
        this.t_hora_recepcion               = serviciosRequierenCotizacionModel.t_hora_recepcion              || formatDate(new Date(), 'HH:mm:ss', 'en-US');
        this.t_hora_entrega                 = serviciosRequierenCotizacionModel.t_hora_entrega                || '';
        this.n_horas_invertidas             = serviciosRequierenCotizacionModel.n_horas_invertidas            || 0;
        this.n_horas_perdidas               = serviciosRequierenCotizacionModel.n_horas_perdidas              || 0;
        this.s_riesgo                       = serviciosRequierenCotizacionModel.s_riesgo                      || '';
        this.s_comentario_revision_tecnico  = serviciosRequierenCotizacionModel.s_comentario_revision_tecnico || '';
        this.s_comodin                      = serviciosRequierenCotizacionModel.s_comodin                     || '';
        this.s_img_firma_inicial            = serviciosRequierenCotizacionModel.s_img_firma_inicial           || '';
        this.s_img_firma_final              = serviciosRequierenCotizacionModel.s_img_firma_final             || '';
        this.b_con_cita                     = serviciosRequierenCotizacionModel.b_con_cita                    || 0;
        this.b_activo                       = serviciosRequierenCotizacionModel.b_activo                      || 0;
        this.n_duracion_recepcion           = serviciosRequierenCotizacionModel.n_duracion_recepcion          || 0;
        this.t_hora_inicio_recepcion        = serviciosRequierenCotizacionModel.t_hora_inicio_recepcion       || '';
        this.t_hora_fin_recepcion           = serviciosRequierenCotizacionModel.t_hora_fin_recepcion          || '';
        this.id_cita                        = serviciosRequierenCotizacionModel.id_cita                       || 0;
        this.s_estatus_cita                 = serviciosRequierenCotizacionModel.s_estatus_cita                || '';
        this.d_fecha_cita                   = serviciosRequierenCotizacionModel.d_fecha_cita                  || formatDate(new Date(), 'yyyy-MM-dd', 'en-US');
        this.t_hora_cita                    = serviciosRequierenCotizacionModel.t_hora_cita                   || formatDate(new Date(), 'HH:mm:ss', 'en-US');
        this.s_qr_cita                      = serviciosRequierenCotizacionModel.s_qr_cita                     || '';
        this.id_cliente                     = serviciosRequierenCotizacionModel.id_cliente                    || 0;
        this.s_nombre                       = serviciosRequierenCotizacionModel.s_nombre                      || '';
        this.s_apellido_paterno             = serviciosRequierenCotizacionModel.s_apellido_paterno            || '';
        this.s_apellido_materno             = serviciosRequierenCotizacionModel.s_apellido_materno            || '';
        this.n_telefono                     = serviciosRequierenCotizacionModel.n_telefono                    || '';
        this.s_direccion                    = serviciosRequierenCotizacionModel.s_direccion                   || '';
        this.id_vehiculo                    = serviciosRequierenCotizacionModel.id_vehiculo                   || 0;
        this.s_marca_vehiculo               = serviciosRequierenCotizacionModel.s_marca_vehiculo              || '';
        this.s_modelo_vehiculo              = serviciosRequierenCotizacionModel.s_modelo_vehiculo             || '';
        this.n_anio                         = serviciosRequierenCotizacionModel.n_anio                        || 0;
        this.s_placa                        = serviciosRequierenCotizacionModel.s_placa                       || '';
        this.s_vin                          = serviciosRequierenCotizacionModel.s_vin                         || '';
        this.s_kilometraje                  = serviciosRequierenCotizacionModel.s_kilometraje                 || 0;
        this.id_servicio                    = serviciosRequierenCotizacionModel.id_servicio                   || 0;
        this.s_tipo_servicio                = serviciosRequierenCotizacionModel.s_tipo_servicio               || '';
        this.s_servicio                     = serviciosRequierenCotizacionModel.s_servicio                    || '';
        this.s_descripcion                  = serviciosRequierenCotizacionModel.s_descripcion                 || '';
        this.n_precio                       = serviciosRequierenCotizacionModel.n_precio                      || 0;
        this.n_puntos_lealtad               = serviciosRequierenCotizacionModel.n_puntos_lealtad              || 0;
        this.n_duracion_horas               = serviciosRequierenCotizacionModel.n_duracion_horas              || 0;
        this.n_duracion_dias                = serviciosRequierenCotizacionModel.n_duracion_dias               || 0;
        this.id_tipo_revision               = serviciosRequierenCotizacionModel.id_tipo_revision              || 0;
        this.id_empleado                    = serviciosRequierenCotizacionModel.id_empleado                   || 0;
        this.s_nombre_asesor                = serviciosRequierenCotizacionModel.s_nombre_asesor               || '';
        this.s_apellido_paterno_asesor      = serviciosRequierenCotizacionModel.s_apellido_paterno_asesor     || '';
        this.s_apellido_materno_asesor      = serviciosRequierenCotizacionModel.s_apellido_materno_asesor     || '';
        this.id_sucursal                    = serviciosRequierenCotizacionModel.id_sucursal                   || 0;
        this.s_sucursal                     = serviciosRequierenCotizacionModel.s_sucursal                    || '';
        this.s_direccion_sucursal           = serviciosRequierenCotizacionModel.s_direccion_sucursal          || '';
        this.id_estatus_orden_servicio      = serviciosRequierenCotizacionModel.id_estatus_orden_servicio      || 0;
        this.s_estatus_orden_servicio       = serviciosRequierenCotizacionModel.s_estatus_orden_servicio       || '';
        this.id_nivel_combustible           = serviciosRequierenCotizacionModel.id_nivel_combustible           || 0;
        this.s_nivel_combustible            = serviciosRequierenCotizacionModel.s_nivel_combustible            || '';
        this.id_estatus_proceso             = serviciosRequierenCotizacionModel.id_estatus_proceso             || 0;
        this.s_estatus_proceso              = serviciosRequierenCotizacionModel.s_estatus_proceso              || '';
        this.id_clase_refaccion             = serviciosRequierenCotizacionModel.id_clase_refaccion            || 0;
        this.s_clase_refaccion              = serviciosRequierenCotizacionModel.s_clase_refaccion             || '';
        this.id_tipo_proveedor_refacciones  = serviciosRequierenCotizacionModel.id_tipo_proveedor_refacciones  || 0;
        this.s_tipo_proveedor_refacciones   = serviciosRequierenCotizacionModel.s_tipo_proveedor_refacciones   || '';
        this.id_promocion                   = serviciosRequierenCotizacionModel.id_promocion                   || 0;
        this.s_promocion                    = serviciosRequierenCotizacionModel.s_promocion                    || '';
        this.n_porcentaje_descuento         = serviciosRequierenCotizacionModel.n_porcentaje_descuento         || 0;
        this.id_anticipo                    = serviciosRequierenCotizacionModel.id_anticipo                    || 0;
        this.n_importe                      = serviciosRequierenCotizacionModel.n_importe                      || 0;
        this.s_nombre_imagen                = serviciosRequierenCotizacionModel.s_nombre_imagen                || '';
        this.s_url_imagen                   = serviciosRequierenCotizacionModel.s_url_imagen                   || '';
    }


    public getRandomID(): number {
        const S4 = () => {
        return ((1 + Math.random()) * 0x10000) | 0;
        };
        return S4() + S4();
    }
}
